version: '3'
services:
  db:
    command: postgres
    entrypoint: ./upgrade/docker-upgrade-entrypoint-wrapper.sh
    environment:
      POSTGRES_DB: some_app
      POSTGRES_INITDB_ARGS: --data-checksums
    image: postgres:12-alpine
    volumes:
      - './initdb:/docker-entrypoint-initdb.d:ro'
      - './upgrade:/upgrade:ro'
      - './pgdata:/var/lib/postgresql/data'
